# Generated by Django 3.2.15 on 2023-02-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('categoryID', models.IntegerField(help_text='类别ID', max_length=4, primary_key=True, serialize=False, unique=True)),
                ('goodsCategory', models.CharField(help_text='类别名', max_length=30, unique=True)),
                ('desc', models.TextField(help_text='类别描述', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('stone', '青铜'), ('silver', '白银'), ('gold', '黄金'), ('diamond', '钻石'), ('king', '王者')], max_length=16, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['created_by'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('goodsName', models.CharField(max_length=30, unique=True)),
                ('goodsRemark', models.TextField(null=True)),
                ('goodsPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('goodsSale', models.IntegerField(default=0)),
                ('goodsPic', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goodsCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goodscategory')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
