# Generated by Django 3.2.15 on 2023-02-24 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_by'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='add_time',
        ),
        migrations.AddField(
            model_name='goods',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
