# Generated by Django 3.2.15 on 2023-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('stone', '青铜'), ('silver', '白银'), ('gold', '黄金'), ('diamond', '钻石'), ('king', '王者')], max_length=16, null=True),
        ),
    ]
