# Generated by Django 3.2.15 on 2023-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_goodscategory_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
