# Generated by Django 3.2.15 on 2023-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230206_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
