# Generated by Django 3.2.15 on 2023-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230227_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
