# Generated by Django 3.2.15 on 2023-02-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(default='null', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
