# Generated by Django 4.1.6 on 2023-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_userid_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
