# Generated by Django 3.2.15 on 2023-02-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_id_alter_user_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('goodsName', models.CharField(max_length=30, unique=True)),
                ('goodsRemark', models.TextField(null=True)),
                ('goodsPrice', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('goodsSale', models.IntegerField(default=0)),
                ('goodsPic', models.CharField(blank=True, max_length=100, null=True)),
                ('goodsCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goodscategory')),
            ],
        ),
    ]
