# Generated by Django 3.2.15 on 2023-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_goods_goodscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
