# Generated by Django 3.2.15 on 2023-02-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230220_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goodsCategory',
            new_name='goodsCategoryId',
        ),
    ]
