# Generated by Django 3.2.15 on 2023-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_goodscategory_goods_goodscategoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
