# Generated by Django 4.1.6 on 2023-02-22 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_goodscategory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='desc',
            field=models.TextField(help_text='类别描述', null=True),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category',
            field=models.CharField(help_text='类别名', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='id',
            field=models.AutoField(help_text='类别code', primary_key=True, serialize=False, unique=True),
        ),
    ]
